#!/usr/bin/env bash

set -euo pipefail

source .builder

for file in src/pub.res/*; do

  if [ -f "$file" ]; then

    echo -e "\nCopying $file"
    copy_file "$file" "tgt/pub/${file##*/}"
  fi
done

for dir in src/pub.lib.*/; do

  for file in "$dir"*; do

    if [ -f "$file" ]; then

      echo -e "\nCopying $file"
      copy_file "$file" "tgt/pub/lib/${file##*/}"
    fi
  done
done

for dir in src/pub.*/; do
 
  item="${dir/src/tgt}"
  item="${item//.//}"
  item="${item%/}"

  name="${item##*/}"

  if [ -f "${dir}Handler.java" ]; then

    echo -e "\nBuilding ${dir}Handler.java"
    build_jar "${dir}Handler.java" "${item}.jar"

    echo -e "\nBuilding ${dir}${name}.css"
    build_css "${dir}${name}.css" "${item}.css"

    echo -e "\nBuilding ${dir}${name}.js"
    build_js "${dir}${name}.js" "${item}.js"
  fi
done

echo -e "\nDone"
